name: flutter_onpay_sdk
description: Flutter package to integrate OnPay.ru Visa/MasterCard payment form into your mobile application.
version: 0.0.7
homepage: https://onpay.ru
github: https://github.com/vanitu/flutter_onpay_sdk

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  http: ^1.1.0
  flutter:
    sdk: flutter
  webview_flutter: ^4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
