name: flutter_onpay_sdk
description: Flutter package to integrate OnPay.ru Visa/MasterCard payment form into your mobile application.
version: 0.0.5
homepage: https://onpay.ru
github: https://github.com/vanitu/flutter_onpay_sdk

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  http: ^0.13.4
  flutter:
    sdk: flutter
  webview_flutter: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
